language: node_js
node_js:
  - "node"
  - "10"
  - "8"
after_success: npm run inform-coveralls
# deploy:
#   provider: npm
#   api_key: < travis encrypt YOUR_API_KEY --add deploy.api_key  >
#   skip_cleanup: true
#   on:
#     tags: true
